### ISSUE TITLE
Integration test fails

### ISSUE THREAD

**Issue by frankscholten** [ContainerSolutions/externalsecret-operator#52]
```
[frank@laptop onepassword]$ go test backend_integration_test.go 
Init: Error parsing the OPERATOR_CONFIG env var. unknown backend type: 'onepassword'
E
Errors:

  * /home/frank/go/src/github.com/ContainerSolutions/externalsecret-operator/secrets/onepassword/backend_integration_test.go 
  Line 28: - runtime error: invalid memory address or nil pointer dereference 
  goroutine 6 [running]:
  panic(0x8d9f80, 0xdc2470)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
  command-line-arguments.TestOnePasswordBackend.func1.1()
        /home/frank/go/src/github.com/ContainerSolutions/externalsecret-operator/secrets/onepassword/backend_integration_test.go:29 +0x51
  github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
        /home/frank/go/src/github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls/context.go:97 +0x40d
  github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls.EnsureGoroutineId(0xc000127860)
        /home/frank/go/src/github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls/gid.go:19 +0x108
  github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls.(*ContextManager).SetValues(0xc000073aa0, 0xc000127800, 0xc0000
0f7c0)
        /home/frank/go/src/github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls/context.go:63 +0x14b
  command-line-arguments.TestOnePasswordBackend.func1()
        /home/frank/go/src/github.com/ContainerSolutions/externalsecret-operator/secrets/onepassword/backend_integration_test.go:28 +0x169
  github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
        /home/frank/go/src/github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls/context.go:97 +0x40d
  github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls.EnsureGoroutineId.func1()
        /home/frank/go/src/github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls/gid.go:24 +0x2e
  github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls._m(0x0, 0xc00000f620)
        /home/frank/go/src/github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls/stack_tags.go:108 +0x31
  github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls.github_com_jtolds_gls_markS(0x0, 0xc00000f620)
        /home/frank/go/src/github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls/stack_tags.go:56 +0x35
  github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls.addStackTag(...)
        /home/frank/go/src/github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls/stack_tags.go:49
  github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls.EnsureGoroutineId(0xc0001275c0)
        /home/frank/go/src/github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls/gid.go:24 +0xd6
  github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls.(*ContextManager).SetValues(0xc000073aa0, 0xc000127560, 0xc00000f5e0)
        /home/frank/go/src/github.com/ContainerSolutions/externalsecret-operator/vendor/github.com/jtolds/gls/context.go:63 +0x14b
  command-line-arguments.TestOnePasswordBackend(0xc000134100)
        /home/frank/go/src/github.com/ContainerSolutions/externalsecret-operator/secrets/onepassword/backend_integration_test.go:16 +0xcd
  testing.tRunner(0xc000134100, 0x97cf38)
        /usr/local/go/src/testing/testing.go:865 +0xc0
  created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:916 +0x35a
  
  goroutine 1 [chan receive]:
  testing.(*T).Run(0xc000134100, 0x95f63c, 0x16, 0x97cf38, 0x47baf6)
        /usr/local/go/src/testing/testing.go:917 +0x381
  testing.runTests.func1(0xc000134000)
        /usr/local/go/src/testing/testing.go:1157 +0x78
  testing.tRunner(0xc000134000, 0xc0000bde30)
        /usr/local/go/src/testing/testing.go:865 +0xc0
  testing.runTests(0xc00000f580, 0xdc3450, 0x1, 0x1, 0x0)
        /usr/local/go/src/testing/testing.go:1155 +0x2a9
  testing.(*M).Run(0xc0000dc400, 0x0)
        /usr/local/go/src/testing/testing.go:1072 +0x162
  main.main()
        _testmain.go:42 +0x13e
  
  goroutine 5 [chan receive]:
  github.com/ContainerSolutions/externalsecret-operator/vendor/k8s.io/klog.(*loggingT).flushDaemon(0xdd06a0)
        /home/frank/go/src/github.com/ContainerSolutions/externalsecret-operator/vendor/k8s.io/klog/klog.go:943 +0x8b
  created by github.com/ContainerSolutions/externalsecret-operator/vendor/k8s.io/klog.init.0
        /home/frank/go/src/github.com/ContainerSolutions/externalsecret-operator/vendor/k8s.io/klog/klog.go:403 +0x6c
  


1 total assertion

--- FAIL: TestOnePasswordBackend (0.00s)
FAIL
FAIL    command-line-arguments  0.005s
[frank@laptop onepassword]$ ```

**Comment by frankscholten** [comment]
Fixed in https://github.com/ContainerSolutions/externalsecret-operator/pull/54
